package dev.diligent.app.widget.quotes

val BallKnowledgePreset = signedPreset(
    id = "ball_knowledge",
    name = "Ball Knowledge",
    description = "Game-day mentality from every court and pitch",
    heroPhrases = listOf(
        "BALL DON'T LIE",
        "NEXT PLAY",
        "LOCKED IN",
        "CLUTCH GENES",
        "DEFENSE TRAVELS",
        "EMPTY GYM HOURS",
        "RUN IT BACK",
        "NO OFF-SEASON",
        "GAME TIME",
        "STAY READY",
        "BOX OUT",
        "OVERTIME MINDSET"
    ),
    lines = listOf(
        "Championships are won in the off-season.",
        "Defense travels. Talent takes nights off.",
        "The scoreboard doesn't care how you feel.",
        "Play the next play. The last one is gone.",
        "Ball don't lie, and neither does your practice log.",
        "Sweat in practice so you don't bleed in the game.",
        "Shooters shoot. Miss ten, take the eleventh.",
        "Film doesn't lie. Watch yours.",
        "Every rep is a vote for the player you want to be.",
        "Stars win games. Teams win titles.",
        "Hustle plays don't make highlights. They make wins.",
        "The clock is the only opponent you can't foul.",
        "Play for the name on the front of the jersey.",
        "Box out life. Fight for every rebound.",
        "Fundamentals are boring until they win you the game.",
        "Your first step is quicker when your mind is made up.",
        "Respect every opponent. Fear none.",
        "Pressure is a privilege. Ask anyone on the bench.",
        "You don't rise to the big moment. You fall to your training.",
        "The best ability is availability.",
        "Nobody remembers the warm-up. Everybody remembers the finish.",
        "Winning cures a lot. Preparation causes most of the winning.",
        "Keep your head up and your feet moving.",
        "A great pass makes two people better.",
        "The ball finds the player who works.",
        "Clutch is just preparation meeting a big moment.",
        "You can't coach effort. You have to bring it.",
        "Trash talk ends at the buzzer. Results don't.",
        "Ball knowledge is knowing the game. Wisdom is knowing yourself.",
        "Every season starts at zero-zero.",
        "Legends are built in empty gyms.",
        "The comeback starts with the next possession.",
        "Don't hunt stats. Hunt wins.",
        "Run the floor even when you're tired. Especially then.",
        "Ice in the veins comes from fire in practice.",
        "The best players make the hard look boring.",
        "A defense that talks plays faster than one that doesn't.",
        "If you're not getting better, someone in your position is.",
        "X's and O's win on paper. Will wins on the field.",
        "Respect the game and it respects you back.",
        "The underdog has nothing to lose and everything to prove.",
        "Leave it all on the pitch.",
        "Great teams don't panic when they're down.",
        "Know your role. Then master it.",
        "Short memory for mistakes. Long memory for lessons.",
        "A captain is the first one in and the last one out.",
        "Possession is everything. Value every touch.",
        "The whistle hasn't blown. Keep playing.",
        "Speed kills, but conditioning wins the fourth quarter.",
        "You miss every chance you're too scared to take.",
        "Rings are earned in the months nobody's watching.",
        "Make the extra pass. Make the extra rep.",
        "The bench is a classroom. Pay attention.",
        "Talent sets the floor. Work sets the ceiling.",
        "A hot hand starts with a cold-blooded routine.",
        "Every great dynasty started with one hungry season.",
        "Momentum is real. Build it one stop at a time.",
        "Don't argue with the ref. Answer on the scoreboard.",
        "The game slows down when you've done the homework.",
        "Your body hears everything your mind says. Talk like a winner.",
        "Footwork first. Flash later.",
        "Pre-season you is building playoff you.",
        "Champions adjust. Everyone else complains.",
        "Even the greatest take free throws seriously.",
        "Practice like you're second. Play like you're first.",
        "Rest is part of the program, not a break from it.",
        "Know the playbook cold, then play free.",
        "A road win counts the same as a home win.",
        "One game at a time. One day at a time.",
        "Talent that skips practice loses to effort that doesn't.",
        "Celebrate the assist as loud as the goal.",
        "Bad shots come from bad decisions, not bad luck.",
        "Win the small battles: loose balls, box-outs, first steps.",
        "The crowd can't play for you. Neither can excuses.",
        "Every whistle is a chance to reset.",
        "Great defenders read the hips, not the eyes.",
        "A season is a marathon of sprints.",
        "Stay locked in from tip-off to the final horn.",
        "You don't need to be the loudest to lead.",
        "The weak hand is the difference between good and great.",
        "Get one percent better at one thing every day.",
        "Big games are just normal games with louder noise.",
        "Preparation is the only cheat code.",
        "The best scouting report is the one on your own weaknesses.",
        "Early is on time. On time is late.",
        "Champions get uncomfortable on purpose.",
        "Never lose twice. Learn from the first one.",
        "Conditioning is confidence you can carry into overtime.",
        "Teams that trust each other move the ball faster.",
        "One great half isn't a great game.",
        "Pressure the ball. Pressure the day.",
        "The last two minutes are where reputations are made.",
        "Stats tell you what happened. Film tells you why.",
        "Be the player your coach never has to worry about.",
        "Do the dirty work and the highlights will find you.",
        "Every pro was once an amateur who didn't quit.",
        "A great season is just great weeks stacked together.",
        "Play with your eyes up. Someone is always open.",
        "Wins are rented. Work ethic is owned.",
        "Ball knowledge says study the game. Real knowledge says live it."
    )
)
