package dev.diligent.app.widget.quotes

val ChessMindPreset = signedPreset(
    id = "chess_mind",
    name = "Chess Mind",
    description = "Strategy, patience, and thinking ahead",
    heroPhrases = listOf(
        "THINK AHEAD",
        "CONTROL THE CENTER",
        "NO BLUNDERS",
        "PLAN OVER HOPE",
        "ENDGAME READY",
        "QUIET MOVES",
        "PUSH THE PAWN",
        "TAKE THE INITIATIVE",
        "CASTLE EARLY",
        "ZUGZWANG",
        "LONG GAME",
        "EVERY MOVE MATTERS"
    ),
    lines = listOf(
        "Every move must have a purpose.",
        "Think three moves ahead. Life rewards foresight.",
        "Control the center and the edges follow.",
        "A pawn that keeps moving can become a queen.",
        "Sacrifice the piece, win the position.",
        "Before you play the good move, search for the great one.",
        "Tempo is time. Don't waste it.",
        "Develop your pieces before you attack.",
        "A well-placed threat can do more than the capture itself.",
        "Every blunder teaches you to slow down.",
        "Castle early. Protect your king, protect your peace.",
        "Patience is a positional weapon.",
        "Play the board, not the opponent's reputation.",
        "Quiet positions are where strategy earns its keep.",
        "The endgame rewards those who studied it.",
        "Don't trade your best piece for a quick thrill.",
        "A clear plan beats a brilliant improvisation.",
        "Losses are free lessons if you review them.",
        "Even the king moves one square at a time.",
        "Open files are open opportunities.",
        "Weak squares are weak habits. Fix them.",
        "Initiative wins games. Take it.",
        "Every opening has a counter. Stay curious.",
        "Calculate, don't hope.",
        "The clock is part of the game. Manage it.",
        "Simplify when you're ahead.",
        "Complicate when you're behind.",
        "The quiet move is often the killer move.",
        "Knights love outposts. Find yours.",
        "Bishops need open diagonals. Clear your path.",
        "Doubled pawns, doubled problems.",
        "Rooks belong on open files and the seventh rank.",
        "Study the masters, then make your own moves.",
        "Don't fear the strong opponent. Fear lazy preparation.",
        "A position is only lost when you resign.",
        "Build a strong position and tactics will appear.",
        "Look at your opponent's last move first.",
        "Every piece should be working.",
        "Pressure builds until something cracks.",
        "Count the material, but weigh the activity.",
        "Defend calmly. Counterattack decisively.",
        "One tempo can change everything.",
        "The best players lost a lot while learning.",
        "Prophylaxis: stop the problem before it starts.",
        "Play the position you have, not the one you wanted.",
        "Sometimes the best move is making them move.",
        "Never resign in your head before the board says so.",
        "Every game is a story. Write a good one.",
        "Puzzles build pattern recognition. So does daily practice.",
        "Your king is safe when your pieces work together.",
        "Don't grab poisoned pawns.",
        "A strong center gives you choices.",
        "Trade when it helps, not out of fear.",
        "Long-term thinking beats short-term greed.",
        "The opponent's plan tells you yours.",
        "Space is a resource. Claim it.",
        "A bad plan is better than no plan.",
        "Rest your mind between games. Fresh eyes see more.",
        "Gambits only pay off with follow-up.",
        "Keep your pieces protected and your options open.",
        "Every grandmaster once hung their queen.",
        "Promote your pawns. Promote yourself.",
        "Opposite-colored bishops love a draw.",
        "Small advantages compound into wins.",
        "Sit on your hands. Then double-check.",
        "Plans set direction. Tactics close the deal.",
        "Read the board like a book. Every square has a sentence.",
        "In time trouble, trust your fundamentals.",
        "The strongest move is often the simplest.",
        "A passed pawn is a promise. Push it with support.",
        "Analyze your wins as hard as your losses.",
        "Coordination beats raw power.",
        "Think in plans, not single moves.",
        "Your weaknesses will be found. Fix them first.",
        "Trade down into a winning endgame.",
        "Not every check is an attack worth making.",
        "Respect the threat, even from a pawn.",
        "The best defense is a strong position.",
        "Calm calculation beats emotional moves.",
        "Each move is a decision. Own it.",
        "Patience is the grandmaster of virtues.",
        "A single tempo can be worth a pawn.",
        "The game rewards those who study when no one's watching.",
        "Look for checks, captures, and threats, in that order.",
        "Life is a long game. Don't play it like blitz.",
        "Invest in position, not just material.",
        "Don't move fast just because your opponent did.",
        "Make your opponent solve hard problems.",
        "Your rating is a snapshot. Your effort is the trend.",
        "Even a small edge, held long enough, wins.",
        "A rook on the open file is a road to victory.",
        "Discipline in the opening, creativity in the middle, precision in the end.",
        "Every piece has a role. So do you.",
        "The board resets every game. So does the day.",
        "Think before you touch. In life, touch-move always applies.",
        "Know the line between bold and reckless.",
        "A good loss beats a lucky win.",
        "Mate in one is the reward for many quiet moves.",
        "Reflect, adjust, play again.",
        "Checkmate is just discipline on a board."
    )
)
