package dev.diligent.app.widget.quotes

val CodeMonkPreset = signedPreset(
    id = "code_monk",
    name = "Code Monk",
    description = "Shipping, debugging, and green squares",
    heroPhrases = listOf(
        "SHIP IT",
        "COMMIT DAILY",
        "GREEN SQUARES",
        "READ THE DOCS",
        "DEBUG MODE",
        "BUILD IN PUBLIC",
        "KEEP IT SIMPLE",
        "TESTS PASS",
        "DEEP WORK",
        "REFACTOR",
        "HELLO WORLD",
        "ZERO BUGS"
    ),
    lines = listOf(
        "Ship it. Then make it better.",
        "Working first. Clean second. Fast third.",
        "Every bug is a lesson you haven't learned yet.",
        "Read the error message. All of it.",
        "Commit early. Commit often.",
        "The best code is the code you didn't have to write.",
        "Naming things is hard. Name them anyway, and name them well.",
        "Tests are a love letter to your future self.",
        "'Works on my machine' is not a deployment strategy.",
        "Simple scales. Clever breaks.",
        "Write code that 3 AM you can still debug.",
        "LeetCode today, offer letter tomorrow.",
        "A good commit message is documentation that never goes stale.",
        "Delete code fearlessly. Git remembers.",
        "Measure before you optimize. Guessing is expensive.",
        "Rubber duck it before you message the team.",
        "Your first draft is supposed to be ugly.",
        "Code is read far more often than it is written.",
        "Small pull requests get reviewed. Huge ones get rubber-stamped.",
        "Learn the fundamentals. Frameworks come and go.",
        "Every expert was once stuck on a missing semicolon.",
        "Logs are breadcrumbs for the detective you'll become later.",
        "The terminal is your dojo.",
        "If a task hurts, automate it until it doesn't.",
        "Automate the boring parts. Think about the hard parts.",
        "Forums answer questions. Building answers doubts.",
        "Hours of debugging can save you minutes of reading the docs.",
        "Comment why, not what.",
        "Your side project is the best teacher you'll ever have.",
        "Write it down before you forget why it works.",
        "The compiler is strict because it cares.",
        "Ship small, learn fast.",
        "The cloud is just someone else's computer.",
        "Don't fear the blank file.",
        "Refactor in daylight. Deploy in daylight.",
        "The last ten percent always takes the other ninety.",
        "Learn one new thing per day. Compounding works for brains too.",
        "Edge cases are where the real requirements hide.",
        "Version control is a time machine. Use it.",
        "Keep functions short and intentions clear.",
        "Sleep is a performance optimization.",
        "Build things you would actually use.",
        "Code review is a conversation, not a court.",
        "Don't copy-paste what you don't understand.",
        "A failing test is information, not an insult.",
        "Coffee in, commits out.",
        "Abstraction is a tool, not a trophy.",
        "Every great product started as a hacky prototype.",
        "Ask questions early. Silence is the slowest bug.",
        "Leave the codebase cleaner than you found it.",
        "Deep work beats context switching every time.",
        "Learn your editor's shortcuts. Seconds become hours.",
        "Read other people's code. It's free mentorship.",
        "Errors are signposts, not stop signs.",
        "Don't optimize for lines of code. Optimize for clarity.",
        "Ship the MVP. Polish with feedback.",
        "Explain it to a beginner. That's the real test.",
        "One bug at a time. One commit at a time.",
        "Hard problems get easier after a walk.",
        "Critical systems deserve boring, proven tools.",
        "Your GitHub graph is a diary of discipline.",
        "Green squares are earned, not given.",
        "Algorithms are just patterns you haven't practiced yet.",
        "Think in data structures. The code follows.",
        "Every senior engineer has broken production at least once.",
        "Make it obvious, not clever.",
        "When stuck, shrink the problem.",
        "Don't wait for motivation. Open the editor.",
        "An hour of planning saves a day of rewrites.",
        "Keep your dependencies few and your tests many.",
        "Design for deletion.",
        "Readable beats impressive.",
        "The best debugger is a good night's sleep.",
        "Profile, then optimize.",
        "Learn Git deeply. It will save you someday.",
        "Write the test that would have caught the bug.",
        "Programming is problem solving with a keyboard.",
        "Tutorials teach syntax. Projects teach engineering.",
        "Undefined is not a function, and excuses are not a plan.",
        "Quantum, classical, or JavaScript: logic is logic.",
        "Build in public. Learn in public.",
        "Consistency compiles. Motivation throws exceptions.",
        "Merge conflicts are conversations you postponed.",
        "A stack trace is a map. Follow it.",
        "Every quick fix deserves a ticket.",
        "Know when to stop gold-plating.",
        "The best time to write docs is right after you solve it.",
        "Pair programming doubles the eyes and halves the bugs.",
        "Your future teammates will thank you for clear names.",
        "Code is temporary. Craft is permanent.",
        "Ship, measure, learn, repeat.",
        "Respect the null. It will humble you.",
        "Hello World was your first step. Keep walking.",
        "Fix the cause, not the symptom.",
        "Complexity is easy. Simplicity takes skill.",
        "Learn to love the debugger.",
        "Write less, think more.",
        "Every keystroke is a chance to get better.",
        "Two green builds in a row is a good day. Two hundred is a career.",
        "git commit -m 'showed up again'"
    )
)
