package dev.diligent.app.widget.quotes

val FounderModePreset = signedPreset(
    id = "founder_mode",
    name = "Founder Mode",
    description = "Building, shipping, and staying alive",
    heroPhrases = listOf(
        "FOUNDER MODE",
        "SHIP WEEKLY",
        "TALK TO USERS",
        "DEFAULT TO ACTION",
        "BUILD > TALK",
        "CASH IS OXYGEN",
        "STAY LEAN",
        "MAKE IT INEVITABLE",
        "FOCUS",
        "EXECUTE",
        "SMALL BETS",
        "EXTEND THE RUNWAY"
    ),
    lines = listOf(
        "Build something people actually want.",
        "Talk to users. Then talk to them again.",
        "Launched beats perfect.",
        "Ideas are cheap. Execution is expensive.",
        "Default to action.",
        "The market is the final judge.",
        "Solve a real problem and revenue follows.",
        "Fundraising is a means, not a milestone.",
        "If version one feels polished, you probably shipped too late.",
        "Hire slow. Fire fast.",
        "Culture is what you do when it's hard.",
        "Burn rate is a countdown. Respect it.",
        "Focus is saying no to good ideas.",
        "Early on, do the unscalable thing. It teaches you the scalable one.",
        "A small group of fans beats a big crowd of shrugs.",
        "Every no gets you closer to the right yes.",
        "Speed is a moat when you're small.",
        "Build the product, then build the company.",
        "Cash flow is oxygen.",
        "Ship weekly. Learn weekly.",
        "Founders are paid in problems.",
        "Make something you'd pay for.",
        "Pivot on data, not on panic.",
        "The best pitch is traction.",
        "A great product with no distribution is a secret.",
        "Your real competitor is usually indifference.",
        "Write things down. Clarity scales.",
        "Know the date your money runs out. Then move it.",
        "Small teams move mountains when they're aligned.",
        "Customers don't care about your roadmap. They care about their pain.",
        "Fall in love with the problem, not your solution.",
        "Every great company started as a side project or a crazy idea.",
        "The best time to start was yesterday. The next best is today.",
        "Measure what matters. Ignore vanity metrics.",
        "Leadership is going first when it's scary.",
        "Trust is the real equity.",
        "Profit is a strong opinion from the market.",
        "Ship it ugly, fix it fast.",
        "Momentum is a founder's best friend.",
        "A clear no is a gift.",
        "Grit outlasts genius in the long run.",
        "Build a team smarter than you.",
        "Revenue solves most problems.",
        "Iterate until it's inevitable.",
        "Nobody cares about your idea until you make them care.",
        "The founder sets the pace.",
        "Every hard conversation you postpone gets harder.",
        "Know your unit economics cold.",
        "Small wins compound into big companies.",
        "Product-market fit feels like pull, not push.",
        "Hold the vision firmly. Hold the plan loosely.",
        "If you're not a little scared, you're not aiming high enough.",
        "Waiting for perfect information is a decision too.",
        "Users vote with their time and money.",
        "Build your network before you need it.",
        "Execution is the strategy.",
        "Sell before you build too much.",
        "Every bottleneck is a lesson about your process.",
        "Keep the burn low and the learning high.",
        "Hire people who grow fast, not just people who start high.",
        "Bad news should travel fastest.",
        "Build moats out of trust and speed.",
        "Startups rarely die from competition. They die from distraction.",
        "Every feature has a cost. Charge it to the roadmap.",
        "Find a way. Then find a cheaper way.",
        "Your company is a reflection of your habits.",
        "Your first hundred customers teach you everything.",
        "Silence the noise. Talk to the people paying you.",
        "Raise money when you can, not when you must.",
        "Make the hard calls early.",
        "Write the memo before the meeting.",
        "Growth hides problems. Downturns reveal them.",
        "A founder's job is to make the next decision.",
        "Keep shipping when the hype dies.",
        "Simplicity sells.",
        "Be the person who closes loops.",
        "Customers remember how you fixed the mistake.",
        "Ambition plus discipline equals a company.",
        "Choose co-founders like you'd choose a life raft.",
        "Your calendar shows your real priorities.",
        "Build for the user you have, not the one you imagine.",
        "Every rejection is market research.",
        "Great founders work hard and still protect their rest.",
        "Learn to sell. Every founder is in sales.",
        "The plan will change. The mission shouldn't.",
        "Make the product so good people tell their friends.",
        "Bootstrapped or funded, profit is freedom.",
        "Moving fast is fine. Moving fast in circles is not.",
        "Feedback is fuel, even when it burns.",
        "Think big, start small, move fast.",
        "Run the company you'd want to work for.",
        "Your burn rate should never outpace your learning rate.",
        "One great hire can change the trajectory.",
        "Cut what isn't working before it cuts you.",
        "Hustle is the tax on doing something new.",
        "Fail fast, learn faster, never stop building.",
        "Build tomorrow's company today with small bets.",
        "Discipline today is runway tomorrow.",
        "Stay curious about the customer forever.",
        "Build. Measure. Learn. Repeat."
    )
)
