package dev.diligent.app.widget.quotes

val IronDisciplinePreset = signedPreset(
    id = "iron_discipline",
    name = "Iron Discipline",
    description = "Gym, sweat, and showing up anyway",
    heroPhrases = listOf(
        "NO EXCUSES",
        "EARN THE PUMP",
        "ONE MORE REP",
        "LIFT HEAVY",
        "FORM FIRST",
        "TRUST THE PROGRAM",
        "SWEAT EQUITY",
        "LEG DAY",
        "PR SEASON",
        "BRACE & DRIVE",
        "STRONG MIND",
        "RE-RACK"
    ),
    lines = listOf(
        "The weight doesn't care about your mood. Lift it anyway.",
        "Motivation gets you to the gym. Discipline gets you back.",
        "Strong is built one rep at a time.",
        "Sore today, strong tomorrow.",
        "The bar is honest. It weighs the same on your best and worst days.",
        "Skipping legs is skipping half the work.",
        "Progressive overload works on life too.",
        "You don't find time to train. You make it.",
        "Your body keeps score of every choice.",
        "The kitchen builds what the gym reveals.",
        "Rest days are training days for your recovery.",
        "Form first. Ego last.",
        "Every set you finish is a promise you kept.",
        "Sweat is just weakness checking out.",
        "Consistency beats intensity over a full year.",
        "The last rep is where the change happens.",
        "Strong body, steady mind.",
        "The hardest lift is getting off the couch.",
        "Your only competition is the mirror from last month.",
        "Eat like an athlete. Sleep like it's your job.",
        "Discipline is a light load. Regret is the heavy one.",
        "Earn the pump.",
        "Track your lifts. What gets measured gets moved.",
        "A bad workout beats the one you skipped.",
        "Strength isn't given. It's taken from the bar.",
        "Show up even when you only have sixty percent to give.",
        "The gym is one place where effort always pays.",
        "Lift heavy things. Build a heavy will.",
        "Bodies change slowly. Habits change fast. Start there.",
        "Warm up like a pro. Train like a beast.",
        "Don't wish for it. Rep for it.",
        "Protein, sleep, water, repeat.",
        "Chalk up. Lock in. Pull.",
        "Excuses don't burn calories.",
        "You are one workout away from a better mood.",
        "The plates don't move themselves.",
        "Grind now, flex later.",
        "Your future self is watching your form.",
        "Pain is temporary. PRs last.",
        "Brace your core. Brace your life.",
        "Doubt kills more lifts than weakness ever will.",
        "Two plates started with an empty bar.",
        "Progress photos don't lie. Neither does skipping them.",
        "Stay hungry, stay hydrated.",
        "The pump fades. Discipline stays.",
        "Be stronger than your strongest excuse.",
        "Hit the gym before the day hits you.",
        "Your body achieves what your mind believes.",
        "Tired is a feeling, not a fact.",
        "No shortcuts. Only squats.",
        "Grip it like you mean it.",
        "Small plates add up to big numbers.",
        "Train ugly if you have to. Just train.",
        "One more rep than yesterday.",
        "Muscles grow when you rest. Character grows when you don't quit.",
        "The mirror shows today. The logbook shows the journey.",
        "A strong back carries heavy days.",
        "Deadlift the day.",
        "Results come from the reps you didn't want to do.",
        "Keep your head neutral and your heart full.",
        "Respect the rack. Re-rack your weights.",
        "Earn your rest between sets and between seasons.",
        "You can't out-train a bad diet.",
        "Every champion was once a beginner with sore arms.",
        "Choose what you want most over what you want now.",
        "Strength is a skill. Practice it.",
        "Take the stairs. Take the hard set.",
        "Rome wasn't built in a day, and neither were your quads.",
        "Breathe, brace, drive.",
        "Train for the version of you that doesn't quit.",
        "The weight room teaches patience in pounds.",
        "Leave your ego at the door and your excuses in the car.",
        "Sweat now, shine later.",
        "Recovery isn't lazy. It's strategic.",
        "Lift with purpose, not just for pictures.",
        "Your heart is a muscle too. Train it.",
        "Feel the burn, then finish the set.",
        "You don't have to be extreme. Just consistent.",
        "Make your warm-up someone else's workout.",
        "The barbell builds bones, grit, and humility.",
        "Drink water. Lift weights. Mind your business.",
        "Progress over perfection, rep after rep.",
        "Fall in love with the process and the results will follow.",
        "You can't flex on a weak foundation.",
        "Wake up. Work out. Win the day.",
        "The gym doesn't close on the days you feel weak.",
        "Strength makes every other part of life a little lighter.",
        "Today's warm-up was last year's max.",
        "Trust the program. Then run it for a year.",
        "Calories in, effort out.",
        "Pull your weight, in the gym and in life.",
        "Hustle for that muscle.",
        "Every drop of sweat is a deposit.",
        "Champions train. Complainers watch.",
        "Your limits are suggestions you haven't tested yet.",
        "Be the hardest worker in the gym, not the loudest.",
        "Strength lives just past the point you wanted to stop.",
        "Log the set. Then beat it next week.",
        "Light weight. Heavy discipline.",
        "Iron sharpens iron. Find your gym family."
    )
)
