package dev.diligent.app.widget.quotes

val LateNightGrindPreset = signedPreset(
    id = "late_night_grind",
    name = "Late Night Grind",
    description = "After-hours focus for night owls",
    heroPhrases = listOf(
        "NIGHT SHIFT",
        "WHILE THEY SLEEP",
        "MIDNIGHT OIL",
        "DARK MODE",
        "3 AM CLARITY",
        "MOON UP, HEAD DOWN",
        "AFTER HOURS",
        "NO AUDIENCE",
        "OWL MODE",
        "LATE & LOCKED IN",
        "NEON FOCUS",
        "SUNRISE SOON"
    ),
    lines = listOf(
        "While they sleep, we build.",
        "The city lights are on. So is the work ethic.",
        "Midnight oil burns brightest for the hungry.",
        "2 AM thoughts. 6 AM execution.",
        "The night is quiet. Your ambition doesn't have to be.",
        "The silence of the night is the loudest motivation.",
        "Dreams need a night shift.",
        "Stars only shine in the dark. So can you.",
        "Some build empires in daylight. Some build them after hours.",
        "The grind doesn't clock out.",
        "Lights off, screen on, goals in sight.",
        "One more chapter. One more problem. One more rep.",
        "Stay up for the work, never just for the scroll.",
        "Night shifts make day-one legends.",
        "The moon is a witness to every quiet grind.",
        "Energy drinks are temporary. Purpose is renewable.",
        "Earn your sleep by finishing the work.",
        "When the world logs off, log in to your goals.",
        "Coffee at midnight, clarity at dawn.",
        "The night has no meetings. Make it count.",
        "Grind in the dark so you can shine in the light.",
        "Late nights now, freedom later.",
        "Nobody posts the 1 AM study session. Do it anyway.",
        "The quietest hours hold the loudest progress.",
        "Sleep is earned, not owed.",
        "Neon lights, focused mind.",
        "Midnight is just another deadline you can beat.",
        "Turn the TV off. Turn the vision on.",
        "Owls aren't lazy. They just work different hours.",
        "The streetlights flicker. Your focus shouldn't.",
        "You're one late night away from a breakthrough.",
        "Work while the city dreams about it.",
        "The best playlists are made for 3 AM focus.",
        "Darkness doesn't stop the driven.",
        "Your competition is asleep. Use that.",
        "Rest when the mission's done. Then rest well.",
        "The night is long. So is your ambition.",
        "Burn the midnight oil, not your bridges.",
        "Every great story has a chapter written after midnight.",
        "Headphones in, world out.",
        "Grind now. Recover smart. Repeat.",
        "The night belongs to builders.",
        "Some nights you win. Some nights you learn.",
        "No audience at 2 AM. Just you and the work.",
        "Late night discipline, early morning results.",
        "When you can't sleep, build something.",
        "Moonlight is free. So is effort.",
        "The midnight hour separates wishers from workers.",
        "Quiet streets, loud dreams.",
        "Every night session is a brick in tomorrow's empire.",
        "Keep the lamp on until the goal is lit.",
        "Night owls build different.",
        "The hours are short. Make them heavy.",
        "Fatigue fades. Finished work stays.",
        "The clock says late. Your goals say now.",
        "A blue screen glow and a burning goal.",
        "Sacrifice the scroll, not the sleep.",
        "Study by lamplight like the legends did.",
        "The night is a blank page. Write on it.",
        "Work quietly through the night. Let the sunrise announce it.",
        "Behind every overnight success are many overnight sessions.",
        "11:59 PM is still today. Finish strong.",
        "Grind smart: water, focus, then sleep.",
        "The world feels like yours at 3 AM.",
        "Dark mode, bright future.",
        "Keep pushing until the sky turns blue.",
        "Fuel the fire, then rest the flame.",
        "You don't need the sun to make progress.",
        "When the house is asleep, the dream is awake.",
        "Silent hours, serious work.",
        "A late night with purpose beats an early morning without one.",
        "The city sleeps. The hustle breathes.",
        "Turn restless energy into relentless progress.",
        "The best ideas often show up after midnight.",
        "Ambition keeps strange hours.",
        "Finish the task, then let the night take you.",
        "Sleep is part of the grind. Protect it.",
        "Moon up. Head down. Work in.",
        "The late shift builds the long career.",
        "Under the moon, excuses look smaller.",
        "Night is the editor of the day's ambition.",
        "Low light, high focus.",
        "A quiet room is a loud opportunity.",
        "Logging hours the world won't see.",
        "The grind has no time zone.",
        "If you're up anyway, make it count.",
        "Midnight motivation, morning discipline.",
        "Keep going. Sunrise is on its way.",
        "The dark is where roots grow.",
        "Work in the shadows. Rise in the spotlight.",
        "Close the loop before you close your eyes.",
        "Tonight's effort is tomorrow's confidence.",
        "Night grind, day shine.",
        "The stars keep you company. Keep working.",
        "One focused night can outwork a lazy week.",
        "Stay up with purpose or go to bed with peace.",
        "Night owls don't need permission to fly.",
        "The night rewards those who show up for it.",
        "Set the alarm. Shut the laptop. Win again tomorrow."
    )
)
