package dev.diligent.app.widget.quotes

val SamuraiCodePreset = signedPreset(
    id = "samurai_code",
    name = "Samurai Code",
    description = "Honor, patience, and the daily path",
    heroPhrases = listOf(
        "BUSHIDO",
        "SHARPEN DAILY",
        "HONOR FIRST",
        "SEVEN DOWN, EIGHT UP",
        "STILL WATER",
        "ONE CUT",
        "WALK THE PATH",
        "DUTY OVER DESIRE",
        "SILENT BLADE",
        "BEGINNER'S MIND",
        "FORGE ON",
        "NO RETREAT"
    ),
    lines = listOf(
        "The sword is sharpened by a thousand quiet mornings.",
        "Do not fear death. Fear an unlived life.",
        "Victory belongs to the one who prepared in silence.",
        "A warrior's word is heavier than his blade.",
        "Polish your spirit as you polish your steel.",
        "Train until the technique forgets you are there.",
        "One committed cut beats a hundred hesitant ones.",
        "Calm water reflects the moon clearly. So does a calm mind.",
        "Honor is not given. It is kept.",
        "Bow to your opponent. Then do not hold back.",
        "Discipline is the armor no one can see.",
        "Every morning, decide again to walk the path.",
        "Patience is the strongest weapon in a long war.",
        "The master was once a student who refused to stop.",
        "Fall seven times. Stand up eight.",
        "Strike when the moment is right, not when the ego is loud.",
        "A clouded mind cannot see the opening.",
        "Loyalty is the root. Courage is the branch.",
        "Respect the dojo, respect the craft, respect yourself.",
        "Speak little. Train much.",
        "The path has no shortcuts, only steps.",
        "Your greatest opponent wears your face.",
        "In battle and in life, footing is everything.",
        "Win without fighting when you can. Fight fully when you must.",
        "A blade left unused rusts. So does a talent.",
        "Empty your cup before you ask to be taught.",
        "Rise before the sun. The day belongs to the early.",
        "The warrior is gentle at home and fierce in the field.",
        "Stillness before the strike. Clarity in the strike.",
        "Know when to sheathe the sword.",
        "Do every small thing as if it were the only thing.",
        "Courage without wisdom is just recklessness.",
        "Bend like bamboo. Do not break.",
        "Your breath is your anchor. Return to it.",
        "The cherry blossom falls at its peak. Live fully now.",
        "Duty before desire.",
        "Swing ten thousand times. Then swing again.",
        "There is no rank without the work beneath it.",
        "Accept the outcome before the battle. Then fight freely.",
        "A true warrior does not boast. He arrives.",
        "Mastery is repetition with attention.",
        "Seek the way in everything you do.",
        "Keep your blade clean and your conscience cleaner.",
        "Defeat is a teacher who demands respect.",
        "The strongest stance is the balanced one.",
        "Train the body, temper the mind, guard the heart.",
        "Forging takes a season. Polishing takes a lifetime.",
        "Do not regret the battle you chose.",
        "Silence can be the sharpest reply.",
        "When you are ready to learn, the training never ends.",
        "The wanderer drifts. The disciplined one walks with purpose.",
        "One honorable act outweighs a thousand promises.",
        "Your true enemy is impatience.",
        "The way of the warrior is found in daily practice.",
        "Face the wind. Lean forward.",
        "A warrior chooses his battles and his words.",
        "Perfect the basics until they become invisible.",
        "Strength serves. Pride destroys.",
        "To protect others, first master yourself.",
        "Fear sharpens the mind if you hold it still.",
        "The dojo floor remembers every drop of sweat.",
        "Act with intention. Rest with intention.",
        "Honor the teachers who were hard on you.",
        "Even the mountain was built grain by grain.",
        "Cut away what does not serve the path.",
        "A warrior does not complain about the weather.",
        "Spirit first, technique second, strength third.",
        "The quiet blade is the most feared.",
        "Prepare as if you will meet your greatest opponent today.",
        "Victory is decided before the sword leaves the sheath.",
        "Turn your fear into focus.",
        "Train in the rain so you can fight in any weather.",
        "Keep the beginner's mind even at the highest rank.",
        "Restraint is power under control.",
        "The road of mastery is long. Walk it daily.",
        "Walk softly. Carry discipline.",
        "Each day, let yesterday's excuses die.",
        "Respect is the first technique taught and the last mastered.",
        "Let your actions bow before your words.",
        "A warrior's rest is as deliberate as his strike.",
        "The sharpest edge is a focused mind.",
        "Serve something larger than yourself.",
        "Today's sweat is tomorrow's honor.",
        "Hold your ground with dignity.",
        "Train when it is easy. Train harder when it is not.",
        "There is no secret scroll. There is only practice.",
        "Harmony in the body brings harmony in the battle.",
        "Do not chase the opponent. Read him.",
        "Live so that you never need to explain your honor.",
        "Calm hands, burning heart.",
        "The disciplined warrior sleeps well.",
        "A true path may be walked alone, but never in vain.",
        "Every scar is a lesson written in skin.",
        "Draw the sword only with purpose.",
        "Your posture is your first statement.",
        "The flame of resolve must be fed daily.",
        "Be like the river: soft, persistent, unstoppable.",
        "Stand straight. Look forward. Advance.",
        "Defeat costs little. Ignoring its lesson costs everything.",
        "The warrior's day ends in reflection and begins in resolve."
    )
)
