package dev.diligent.app.widget.quotes

val StoicMindPreset = signedPreset(
    id = "stoic_mind",
    name = "Stoic Mind",
    description = "Calm, control, and character",
    heroPhrases = listOf(
        "MEMENTO MORI",
        "AMOR FATI",
        "CONTROL THE CONTROLLABLE",
        "STAY CALM",
        "ENDURE",
        "ACT WELL",
        "VIRTUE IN REPS",
        "RESPOND, DON'T REACT",
        "WANT LESS",
        "STILLNESS",
        "DUTY FIRST",
        "STEADY MIND"
    ),
    lines = listOf(
        "You control your effort, not the outcome.",
        "Every obstacle is training wearing a disguise.",
        "Suffering lives more in the mind than in the moment.",
        "Don't wish for an easier life. Build a stronger self.",
        "Measure today by your effort. Tomorrow will measure the results.",
        "Calm is a skill. Practice it under pressure.",
        "You can't control the wind, but you can trim the sails.",
        "Stop debating what's right. Go do it.",
        "Don't let rude people teach you rudeness.",
        "Memento mori. The clock is running. Use it.",
        "Amor fati. Love whatever the day hands you.",
        "Your mind takes the shape of what you think about most.",
        "Anger is expensive. Pay for it rarely.",
        "Want less. Have more peace.",
        "Hardship is a gym for character.",
        "Opinions are not facts. Most of them aren't even yours.",
        "Act well the part you're given.",
        "Every morning is a fresh draft.",
        "Discipline is freedom from your own impulses.",
        "If it's not in your control, it's not your concern.",
        "Complaining is rehearsing the pain.",
        "You lose nothing you were never promised.",
        "Be tolerant with others and strict with yourself.",
        "Good character is the only possession no one can take.",
        "Praise fades. Principles remain.",
        "Prepare for storms while the sky is clear.",
        "Imagine the loss. Then appreciate what you have.",
        "Most fears never arrive. Stop paying for them in advance.",
        "Live each day as a complete life.",
        "The present moment is all you can actually hold.",
        "Insults only land if you agree to catch them.",
        "What you do in small moments is who you really are.",
        "Pain is information. Panic is optional.",
        "Be the calmest person in the room.",
        "Duty first. Comfort later.",
        "Luxury is a habit that slowly becomes a cage.",
        "Learn to be content with enough.",
        "Your reaction is the only part of the story you write.",
        "Virtue is built in reps, like muscle.",
        "Stop demanding the world obey you. Work with what comes.",
        "The wise accept the rain and carry an umbrella.",
        "Fortune lends. It never gives. Hold things lightly.",
        "Time is the one resource you can't earn back.",
        "A day without reflection is a day without a lesson.",
        "Stop preparing to live. Start living.",
        "Your habits are writing your future in real time.",
        "Be slow to anger and quick to understand.",
        "The ego wants applause. The soul wants growth.",
        "You were not built for comfort. You were built for purpose.",
        "Endure what you must. Change what you can.",
        "Silence is often the strongest reply.",
        "Don't let a moment's pleasure cost a lifetime's peace.",
        "Take the hit. Learn the lesson. Move forward.",
        "Envy is a thief that robs you of your own life.",
        "Do what's right, even when no one sees it.",
        "A prepared mind is rarely surprised.",
        "Every loss is a teacher in plain clothes.",
        "Speak only when it improves the silence.",
        "Wealth is not having more. It's needing less.",
        "Worry is paying interest on a debt you may never owe.",
        "Keep your principles where you can reach them every day.",
        "Be indifferent to what makes no difference.",
        "Discomfort chosen today prevents disaster tomorrow.",
        "You can be knocked down without being defeated.",
        "A steady mind is worth more than a fast one.",
        "Let your actions argue for you.",
        "Treat setbacks as tuition, not punishment.",
        "Zoom out to the big picture. Your problem shrinks.",
        "Nothing outside you can disturb you without permission.",
        "Respond, don't react.",
        "Integrity is when belief and action match.",
        "Gratitude turns what you have into enough.",
        "A short temper buys a long regret.",
        "Not everything deserves a reaction.",
        "Your peace is your responsibility.",
        "Train your mind as hard as your body.",
        "The worst thing that happened is already over.",
        "Be the rock the waves keep breaking against.",
        "Keep a quiet mind in a loud world.",
        "Do the work. Detach from the applause.",
        "The present is enough. Stop borrowing tomorrow's worries.",
        "Choose courage over comfort every time it counts.",
        "Accept the season you're in. Seasons change.",
        "When criticized, check if they're right. Then move on.",
        "Simplicity is a form of strength.",
        "Self-mastery is the first victory.",
        "You become what you repeatedly tolerate.",
        "Your life is the only argument for your philosophy that matters.",
        "Every day, rehearse being the person you want to become.",
        "The night is for review. The morning is for resolve.",
        "Fame is fickle. Character is permanent.",
        "Even a setback can be put to good use.",
        "Reason first, feelings second, action third.",
        "Hold your goals tightly and your expectations loosely.",
        "Courage is fear that kept walking.",
        "Everything changes. Your response is the constant.",
        "Be grateful for hard teachers.",
        "One honest step beats a thousand clever excuses.",
        "Live by reason, not by mood.",
        "Stillness is where clarity lives."
    )
)
