package dev.diligent.app.widget.quotes

val StreetWisdomPreset = signedPreset(
    id = "street_wisdom",
    name = "Street Wisdom",
    description = "Loyalty, respect, and moving smart",
    heroPhrases = listOf(
        "MOVE IN SILENCE",
        "STAY SOLID",
        "TEN TOES DOWN",
        "REAL ONES ONLY",
        "KEEP IT REAL",
        "NO DAYS OFF",
        "BET ON YOURSELF",
        "STAY HUNGRY",
        "WATCH & LEARN",
        "MAKE MOVES",
        "STAY READY",
        "EARN RESPECT"
    ),
    lines = listOf(
        "Move in silence. Let the results do the talking.",
        "Loyalty is earned in the dark and proven in the light.",
        "Never let the block know your next move.",
        "Respect is a currency. Spend it wisely, earn it daily.",
        "The streets don't owe you anything. Neither does life.",
        "Watch who claps when you win.",
        "Keep your circle small and your vision big.",
        "Real ones stay when the lights go out.",
        "Talk less, observe more. Information is power.",
        "Your word is your bond. Break it once and it stays broke.",
        "Hustle quiet. Shine loud.",
        "Every corner you turn teaches you something.",
        "Don't chase people. Chase purpose.",
        "A loose mouth gets you caught. A closed one gets you nowhere. Speak with purpose.",
        "Pressure reveals who's solid and who's paper.",
        "Nobody's coming to save you. Get up.",
        "Trust actions. Words are cheap on every block.",
        "Stay humble when you eat. Stay hungry when you don't.",
        "The ones who doubted you will ask how you did it.",
        "If it costs you your peace, it's too expensive.",
        "Don't mistake kindness for weakness, or attention for respect.",
        "You can't cheat the grind. It knows how much you put in.",
        "Never get too comfortable. Comfort is where you get caught slipping.",
        "Pick your battles. Some fights aren't worth the bruise.",
        "Real recognize real.",
        "Show up the same way whether they're watching or not.",
        "A snake will smile at you before it bites.",
        "Build in private so nobody can sabotage the blueprint.",
        "Some people only see your shine, never your grind.",
        "Small steps every day beat big talk every weekend.",
        "Your environment shapes you. Choose it or it chooses you.",
        "Stay ten toes down when things get rough.",
        "Patience on the block is survival. Patience in life is a superpower.",
        "Don't let a bad day make you a bad person.",
        "A setback on the corner is a lesson for the long road.",
        "Hard times build hard people. Stay soft with the ones who matter.",
        "Plan for the worst. Work for the best.",
        "Don't flex what you can't protect.",
        "Money talks, but discipline makes it listen.",
        "Stay ready so you never have to get ready.",
        "Keep receipts, not grudges.",
        "Not everybody who eats with you is hungry for your success.",
        "Your past is a lesson, not a life sentence.",
        "Walk like you've been there before.",
        "Fear is a liar with a loud voice.",
        "Make moves, not noise.",
        "The ones who talk the most usually do the least.",
        "Read the room before you speak in it.",
        "Never let your emotions sign the deal.",
        "Bet on yourself when nobody else will.",
        "Learn the game before you try to change it.",
        "Every hustle starts with one yes to yourself.",
        "If they don't respect your time, they won't respect your work.",
        "Stay solid. Diamonds are just coal that didn't quit.",
        "The quiet ones are usually counting.",
        "Don't burn bridges. You might need to cross back someday.",
        "A promise from a liar is still a lie.",
        "Keep your head on a swivel and your goals on lock.",
        "Success is the best revenge, and it's legal.",
        "Know your worth, then add tax.",
        "You don't need a crowd to make history.",
        "Stay out of drama. It doesn't pay rent.",
        "Your hustle should outlast their hate.",
        "Trust is like a mirror. Crack it and you'll always see the line.",
        "Stay low, keep grinding.",
        "Whoever holds the information holds the power.",
        "The street remembers who kept it real.",
        "Discipline is doing it right when nobody's checking.",
        "Not every open door is an invitation.",
        "Moving smart beats moving fast.",
        "Let them underestimate you. It's free advantage.",
        "You can't win a race you never show up for.",
        "Your reputation walks in the room before you do.",
        "One bad decision can cost ten good years.",
        "Real wealth is having nothing to prove.",
        "Never trust a smile that only shows up when you're winning.",
        "Survive first. Then thrive. Then teach.",
        "The grind doesn't care about your excuses.",
        "Consistency is a flex nobody can fake.",
        "You become the average of the people on your corner.",
        "Don't let pride keep you from asking for help.",
        "Hunger is a better teacher than comfort.",
        "When they go low, you go to work.",
        "Protect your peace like it's your last dollar.",
        "If you want a different block, make different moves.",
        "Some lessons you only learn the hard way. Learn them once.",
        "Keep the same energy, up and down.",
        "Every boss was once a worker who refused to stay one.",
        "Stay out of the way of people who are going nowhere.",
        "Opportunity rarely knocks twice on the same door.",
        "Don't trust easy money. It leaves the same way it came.",
        "Your circle should push you, not pull you down.",
        "Respect everybody. Fear nobody.",
        "If it was easy, everybody on the block would do it.",
        "Make your name mean something.",
        "The bag is temporary. The skills are forever.",
        "Learn from the OGs. They already paid for the lessons.",
        "Rise quietly. Let your growth make the noise.",
        "You can lose money and get it back. Lost time stays lost.",
        "Where you start doesn't decide where you finish."
    )
)
