package dev.diligent.app.widget.quotes

val ZenFocusPreset = signedPreset(
    id = "zen_focus",
    name = "Zen Focus",
    description = "Calm attention and deep work",
    heroPhrases = listOf(
        "BE HERE NOW",
        "BREATHE",
        "ONE THING",
        "DEEP WORK",
        "STILL MIND",
        "LESS NOISE",
        "FLOW STATE",
        "SLOW IS SMOOTH",
        "PRESENT",
        "CALM FOCUS",
        "LET GO",
        "RETURN"
    ),
    lines = listOf(
        "Do one thing at a time, and do it fully.",
        "Breathe in clarity. Breathe out noise.",
        "The mind is a lake. Let it settle.",
        "Slow is smooth. Smooth is fast.",
        "Where your attention goes, your life follows.",
        "Silence your phone. Hear your thoughts.",
        "You don't need more time. You need fewer distractions.",
        "Sweep the floor with full attention. That is practice.",
        "Each breath is a new beginning.",
        "Let thoughts pass like clouds.",
        "Deep work is a quiet superpower.",
        "Clutter on the desk, clutter in the mind.",
        "Rest is not idleness. It is preparation.",
        "Notice the moment before you react.",
        "The present has everything you need to begin.",
        "Peace isn't a place you reach. It's how you walk.",
        "One task. One timer. One win.",
        "Let go of what you can't carry.",
        "A focused hour beats a scattered day.",
        "Simplicity creates space for what matters.",
        "Be where your feet are.",
        "The tea tastes best when you only drink tea.",
        "Close the tabs. Open the mind.",
        "Mastery is a quiet, daily return.",
        "Stillness speaks louder than urgency.",
        "Water is soft, yet it carves stone.",
        "You are not your thoughts. You are the one noticing them.",
        "Begin from here. Here is enough.",
        "When you're in a hurry, walk slowly.",
        "Lower the noise and the answers rise.",
        "Let your work be your meditation.",
        "Notifications can wait. Your focus cannot.",
        "A calm mind solves faster.",
        "Gratitude grounds the restless heart.",
        "Unhurried does not mean unproductive.",
        "Empty the mind. Fill the page.",
        "Everything changes. Practice anyway.",
        "Small moments of presence add up to a life.",
        "Breathe before you answer.",
        "Paths appear under walking feet.",
        "Fewer things, done with care.",
        "Focus is choosing what to ignore.",
        "The bell rings. Return to now.",
        "Be gentle with yourself and strict with your attention.",
        "Clarity comes after stillness, not before.",
        "Leave space between tasks for the mind to breathe.",
        "Your energy is precious. Spend it intentionally.",
        "Even the busiest river has a still pool.",
        "When walking, walk. When eating, eat.",
        "Practice presence the way you practice skills.",
        "A single breath can reset a whole day.",
        "Don't push the river. It flows by itself.",
        "Let effort be relaxed and steady.",
        "Tidy your space. Settle your mind.",
        "Sit. Breathe. Begin.",
        "The best ideas arrive in quiet moments.",
        "Patience is a form of focus.",
        "Observe without judgment. Act with intention.",
        "Silence is the soil of insight.",
        "You can't pour from a scattered cup.",
        "Gentle persistence beats frantic effort.",
        "Turn off the noise. Turn on the work.",
        "The moon does not rush, yet it is always on time.",
        "Simplicity is a daily practice.",
        "One mindful hour can change a whole week.",
        "Feel the breath. Find the edge. Stay there.",
        "Let the phone rest face down.",
        "Every distraction declined is a vote for your goals.",
        "Finish the task in front of you before starting the next.",
        "The mind wanders. Bringing it back is the workout.",
        "Look at old problems with new eyes.",
        "Quiet effort builds loud results.",
        "Rest the eyes. Rest the mind. Return.",
        "Let your environment do the remembering.",
        "Breathe slower than the world around you.",
        "A clear desk is an invitation to work.",
        "Presence is the antidote to anxiety.",
        "Let go of the result. Hold onto the practice.",
        "Light the candle. Start the timer. Begin.",
        "Monotasking is the new multitasking.",
        "Calm is contagious. Spread it.",
        "There is time enough for everything that matters.",
        "Each day is a pebble on the path. Place it well.",
        "Your attention is the currency of your life.",
        "Focus sharpens like a blade with use.",
        "Settled minds make clean decisions.",
        "Release your grip on yesterday.",
        "Mindfulness isn't extra time. It's better time.",
        "Choose depth over speed.",
        "Be like the mountain, unmoved by passing weather.",
        "Leave work at the door and arrive home fully.",
        "Take one conscious breath before every new task.",
        "The quiet path is still a path forward.",
        "Balance is not found. It is practiced.",
        "Let the coffee cool. Let the mind settle.",
        "Peace is productive.",
        "Be still enough to hear what you really want.",
        "Flow arrives when distraction leaves.",
        "One page, one breath, one step.",
        "Return to the breath. Return to the work."
    )
)
